### ISSUE TITLE
License Missing

### ISSUE THREAD

**Issue by rosskukulinski** [vigetlabs/Twitter-Bootstrap-for-Omnigraffle#16]
To have more widespread adoption, I recommend adding a license for this package.  Many companies can't use great things like this due to uncertain legal status.

Personally, I would recommend the MIT license (http://opensource.org/licenses/MIT)

**Comment by gaomd** [comment]
Any update on this issue? Since this is not a programming based project, I would recommend the [CreativeCommons license](http://creativecommons.org/licenses/by/4.0/).

**Comment by jacksonfox** [comment]
Thanks for the reminder, added LICENSE.md
