### ISSUE TITLE
Readme has incomplete/outdated file paths

### ISSUE THREAD

**Issue by armchairdeity** [vigetlabs/Twitter-Bootstrap-for-Omnigraffle#17]
According to https://support.omnigroup.com/documentation/omnigraffle/mac/7.1/en/using-and-creating-stencils/, OG 7.18 is now a containerized application, and the paths to the stencil, template, and color folders has changed. In that link the paths are given as:

> If you need to access the Stencils folder from a script you are writing, the Unix path to use is:
> 
> Non-Mac App Store purchases:
> ~/Library/Containers/com.omnigroup.OmniGraffle7/Data/Library/Application\ Support/The\ Omni\Group/OmniGraffle/Stencils
Mac App Store purchases:
~/Library/Containers/com.omnigroup.OmniGraffle7.MacAppStore/Data/Library/Application\ Support/The\ Omni\Group/OmniGraffle/Stencils

**Comment by jacksonfox** [comment]
Hi! The install instructions for Omnigraffle 7 should be the same as Omnigraffle 6 — double click the stencil file and follow the prompts in the app to move it into your Stencil folder. You shouldn't need to move it into the Stencil folder manually.

**Comment by jacksonfox** [comment]
I added a note about Omnigraffle 7 to the README. I was able to install both the stencil and template in Omnigraffle 7 by double clicking the files. I should say that I haven't tested any of these files in Omnigraffle 7 though I expect they should work.
